FROM apache/hive:3.1.3

USER root

# New entrypoint for hive that allows dynamic schema initialization logic
COPY ./metastore_entrypoint.sh /metastore_entrypoint.sh

# Hive config to work with MinIO
COPY ./hive-site.xml /opt/hive/conf/hive-site.xml
COPY ./core-site.xml /opt/hive/conf/core-site.xml

# Download and add the PostgreSQL JDBC driver
RUN apt update && \
    apt-get update && \
    apt-get install -y curl && \
    curl -o /opt/hive/lib/postgresql.jar https://jdbc.postgresql.org/download/postgresql-42.7.1.jar && \
    chmod +x /metastore_entrypoint.sh

EXPOSE 9083

USER hive

ENTRYPOINT ["sh", "-c", "/metastore_entrypoint.sh"]
